/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heladeria5t;

import clases.ConexionMySQL;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gledymar
 */
public class EliminarUsuario extends javax.swing.JFrame {
ConexionMySQL  mysql=new ConexionMySQL();
        Connection cn= mysql.conectar();
    /**
     * Creates new form EliminarUsuario
     */private ImageIcon imageicon;
    public EliminarUsuario() {
        initComponents();
        imageicon= new ImageIcon(getClass().getResource("/imagenes/boton1.png"));
    
        this.setIconImage(imageicon.getImage());
         setLocationRelativeTo(null);
        setResizable(false);
        txtbusqueda.requestFocus();
        setTitle("Eliminacion de Usuario");
        fondos F =new fondos();
        this.add(F,BorderLayout.CENTER);
        this.pack();
        mostrardatos("");
        inabilitar();
    }
    void inabilitar(){
        txtcod.setEnabled(false);
        txtusuario.setEnabled(false);
        txtnombre.setEnabled(false);
        txttipo.setEnabled(false);
       
    }
    void limpiar(){
        this.txtcod.setText("");
        this.txtusuario.setText("");
        this.txtnombre.setText("");
        this.txttipo.setText("");
    }
    
   public void confirmarsalida(){
   int valor= JOptionPane.showConfirmDialog(this,"¿Esta seguro que quiere eliminar a este usuario?", "AVISO",JOptionPane.YES_NO_OPTION);
  if(valor==JOptionPane.YES_OPTION) {
      
  }
  else{
    new inicio().setVisible(true);
    this.dispose();
  }
}
   
void mostrardatos(String valor){
DefaultTableModel modelo= new DefaultTableModel();
modelo.addColumn("Codigo");
modelo.addColumn("Nombre");
modelo.addColumn("usuario");
modelo.addColumn("Tipo de usuario");
tbusuarios.setModel(modelo);
String sql="";
if(valor.equals("")){
sql="SELECT tb_user.id_user,usuario,nombre,tipo FROM tb_user JOIN tb_usuarior JOIN tb_tipousuario WHERE tb_user.id_user=tb_usuarior.id_user AND tb_user.niv_usu=tb_tipousuario.niv_usu ";
}
else{ sql="SELECT tb_user.id_user,usuario,nombre,tipo FROM tb_user JOIN tb_usuarior JOIN tb_tipousuario WHERE (tb_user.id_user=tb_usuarior.id_user AND tb_user.niv_usu=tb_tipousuario.niv_usu) AND ( tb_user.id_user='"+valor+"')";}
String []datos = new String [4];

    try {
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
     while(rs.next()){
         datos[0]=rs.getString(1);
         datos[1]=rs.getString(2);
         datos[2]=rs.getString(3);
         datos[3]=rs.getString(4);
         modelo.addRow(datos);
     
     } tbusuarios.setModel(modelo);
    
    } catch (SQLException ex) {
        Logger.getLogger(EliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuarios = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtbusqueda.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtbusqueda.setForeground(new java.awt.Color(153, 0, 153));
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });

        tbusuarios.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        tbusuarios.setForeground(new java.awt.Color(153, 0, 153));
        tbusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuariosMouseClicked(evt);
            }
        });
        tbusuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbusuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbusuarios);

        btnbuscar.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        jPanel1.setForeground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setText("cod:");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Usuario:");

        txtcod.setEditable(false);
        txtcod.setBackground(new java.awt.Color(255, 204, 255));
        txtcod.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtcod.setForeground(new java.awt.Color(153, 0, 153));

        txtusuario.setEditable(false);
        txtusuario.setBackground(new java.awt.Color(255, 204, 255));
        txtusuario.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(153, 0, 153));

        txtnombre.setEditable(false);
        txtnombre.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(153, 0, 153));

        txttipo.setEditable(false);
        txttipo.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txttipo.setForeground(new java.awt.Color(153, 0, 153));

        btneliminar.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuario)
                    .addComponent(txtnombre)
                    .addComponent(txttipo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btneliminar)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnsalir.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("ELIMINAR USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnbuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnsalir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
   int valor= JOptionPane.showConfirmDialog(this,"¿Esta seguro que quiere eliminar a este usuario?", "AVISO",JOptionPane.YES_NO_OPTION);
  if(valor==JOptionPane.YES_OPTION) {
      int fila = tbusuarios.getSelectedRow();
        String cod="";
        if(fila >=0){
        txtcod.setText(tbusuarios.getValueAt(fila, 0).toString());
        txtusuario.setText(tbusuarios.getValueAt(fila, 1).toString());
        txtnombre.setText(tbusuarios.getValueAt(fila, 2).toString());
        txttipo.setText(tbusuarios.getValueAt(fila, 3).toString());
        cod=tbusuarios.getValueAt(fila,0).toString();
        try{
        PreparedStatement pst= cn.prepareStatement("DELETE tb_user,tb_usuarior,tb_respuestas FROM tb_user JOIN tb_usuarior ON tb_user.id_user=tb_usuarior.id_user JOIN tb_respuestas ON tb_user.id_user=tb_respuestas.id_user WHERE tb_user.id_user='"+cod+"'");
       pst.executeUpdate();
       JOptionPane.showMessageDialog(null,"Eliminación Exitosa");
        limpiar();
       mostrardatos("");
        }
         catch(Exception e){

}       
        }
        else {
        JOptionPane.showMessageDialog(null,"No a seleccionado usuario");
        }
        limpiar();
  }
  else{
    limpiar();
  }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
      mostrardatos(txtbusqueda.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tbusuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbusuariosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbusuariosKeyPressed

    private void tbusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuariosMouseClicked
        int fila = tbusuarios.getSelectedRow();
        if(fila >=0){
            txtcod.setText(tbusuarios.getValueAt(fila, 0).toString());
        txtusuario.setText(tbusuarios.getValueAt(fila, 1).toString());
        txtnombre.setText(tbusuarios.getValueAt(fila, 2).toString());
        txttipo.setText(tbusuarios.getValueAt(fila, 3).toString());
        }
        else {
        JOptionPane.showMessageDialog(null,"No a seleccionado usuario");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbusuariosMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
      new inicio().setVisible(true);
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbusuarios;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
