/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heladeria5t;

import clases.CargarDatos;
import clases.ConexionMySQL;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class PreguntasSeg extends javax.swing.JFrame {

      int i=0;
      
    /**
     * Creates new form PreguntasSeg
     */
      private ImageIcon imageicon;
    public PreguntasSeg() {
        initComponents();
        imageicon= new ImageIcon(getClass().getResource("/imagenes/boton1.png"));
    
        this.setIconImage(imageicon.getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Preguntas de Seguridad");
        fondoUs F=new fondoUs();
        this.add(F,BorderLayout.CENTER);
        this.pack();
    }

    void acceder(String resp1, String resp2){
        ConexionMySQL  mysql=new ConexionMySQL();
        Connection cn= mysql.conectar();
        String sSQL,sSQL1;
       String cap="",cap1="",user="";
       
        sSQL="SELECT tb_user.usuario,tb_user.contraseña FROM tb_preguntas,tb_respuestas,tb_user "
                + "WHERE tb_preguntas.id_preg=tb_respuestas.id_preg "
                + "AND tb_respuestas.id_user=tb_user.id_user AND tb_preguntas.id_preg='"+CargarDatos.getNumpregunta1()+ "'"
                + "AND tb_respuestas.respuestas='"+resp1+"' ;";
        
        sSQL1="SELECT tb_user.usuario,tb_user.contraseña FROM tb_preguntas,tb_respuestas,tb_user "
                + "WHERE tb_preguntas.id_preg=tb_respuestas.id_preg "
                + "AND tb_respuestas.id_user=tb_user.id_user AND tb_preguntas.id_preg='"+CargarDatos.getNumpregunta2()+ "'"
                + "AND tb_respuestas.respuestas='"+resp2+"' ;";
        try{
         
        Statement st = cn.createStatement();
        Statement st1 = cn.createStatement();
        ResultSet rs= st.executeQuery(sSQL);
        ResultSet rs1= st1.executeQuery(sSQL1);
        
        while(rs.next() && rs1.next()){
            user=rs.getString("usuario");
            cap=rs.getString("contraseña");
            cap1=rs1.getString("contraseña");
            
        }
        if(cap.equals("") || cap1.equals("") || !(cap.equals(cap1))){
             JOptionPane.showMessageDialog(null, "Respuestas incorrectas");
        }else{
            
            JOptionPane.showMessageDialog(null, " usuario: "+user+"\n contraseña: "+cap);
            new Usuario().setVisible(true);
            this.dispose();
            
        }
        
        }catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }
    
    String accederPreguntas(int x){
        ConexionMySQL  mysql=new ConexionMySQL();
        Connection cn= mysql.conectar();
        String sSQL;
        String cap="";
        sSQL="SELECT * FROM tb_preguntas"
                + " WHERE id_preg='"+x+"' ";
        try{
         
        Statement st = cn.createStatement();
        ResultSet rs= st.executeQuery(sSQL);
        while(rs.next()){
            cap=rs.getString("pregunta");
        }
        
        }catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    
        return cap;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lpregunta1 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JTextField();
        Lpregunta2 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        butRecuperacion = new org.edisoncor.gui.button.ButtonAction();
        butSalir = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Lpregunta1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta1ActionPerformed(evt);
            }
        });

        Lpregunta2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        butRecuperacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        butRecuperacion.setText("Recuperar usuario");
        butRecuperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRecuperacionActionPerformed(evt);
            }
        });

        butSalir.setText("Salir");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(txtRespuesta1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Lpregunta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lpregunta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lpregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lpregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta1ActionPerformed
        // TODO add your handling code here:
        txtRespuesta1.transferFocus();
    }//GEN-LAST:event_txtRespuesta1ActionPerformed

    private void butRecuperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRecuperacionActionPerformed
        // TODO add your handling code here:
        String resp1=txtRespuesta1.getText();
        String resp2=txtRespuesta2.getText();
        acceder(resp1,resp2);
    }//GEN-LAST:event_butRecuperacionActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        new Usuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         int x=0,y=0;
        
        do{
        for(int i=0;i<2;i++){
            Random r=new Random();
            int na=r.nextInt(4)+1;
            if(i==0)
               x=na;
            
            y=na;
            
            
           }
        }while(x==y);
        CargarDatos.setNumpregunta1(x);
        CargarDatos.setNumpregunta2(y);
        
       Lpregunta1.setText(accederPreguntas(CargarDatos.getNumpregunta1()));
       Lpregunta2.setText(accederPreguntas(CargarDatos.getNumpregunta2()));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntasSeg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lpregunta1;
    private javax.swing.JLabel Lpregunta2;
    private org.edisoncor.gui.button.ButtonAction butRecuperacion;
    private org.edisoncor.gui.button.ButtonAction butSalir;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    // End of variables declaration//GEN-END:variables
}
