/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heladeria5t;


import clases.ConexionMySQL;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gledymar
 */
public class RegistrarUsuario extends javax.swing.JFrame {
        ConexionMySQL  mysql=new ConexionMySQL();
        Connection cn= mysql.conectar();
        private ImageIcon imageicon;
    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario() {
        initComponents();
        mostrarpregunta();
        tipousuario();
        numeros();
        
        imageicon= new ImageIcon(getClass().getResource("/imagenes/boton1.png"));
    
        this.setIconImage(imageicon.getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registro de Usuarios");
        this.pack();
        
    }
    void limpiar(){
      this.txtnick.setText("");
      this.txtpassword1.setText("");
      this.txtpassword2.setText("");
      this.txtcedula.setText("");
      this.txtnombre.setText("");
      this.txtapellido.setText("");
         
      
    }
       
void mostrarpregunta(){
 String sql="SELECT * FROM tb_preguntas";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                while (rs.next()){
                    cmbpregunta1.addItem(rs.getString("pregunta"));
                    cmbpregunta2.addItem(rs.getString("pregunta"));
                    cmbpregunta3.addItem(rs.getString("pregunta"));
                    cmbpregunta4.addItem(rs.getString("pregunta"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
}
void tipousuario(){
String sql="SELECT * FROM tb_tipousuario";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                while (rs.next()){
                    cmbusuario.addItem(rs.getString("tipo"));
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
}

void numeros(){
String c="";
int d,id;
String SQL= "SELECT MAX(id_user) AS id_user FROM tb_user";

Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs= st.executeQuery(SQL);
                if(rs.next()){
                    c=rs.getString("id_user");
                    d=Integer.parseInt(c);
                    id=d+1;
             txtcod.setText(String.valueOf(id));
                }    
            } 
            
            catch (SQLException ex) {
                Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnick = new javax.swing.JTextField();
        txtpassword1 = new javax.swing.JPasswordField();
        txtpassword2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbpregunta1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbpregunta2 = new javax.swing.JComboBox<>();
        cmbpregunta3 = new javax.swing.JComboBox<>();
        cmbpregunta4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbusuario = new javax.swing.JComboBox<>();
        txtrespuesta4 = new javax.swing.JTextField();
        txtrespuesta3 = new javax.swing.JTextField();
        txtrespuesta2 = new javax.swing.JTextField();
        txtrespuesta1 = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setText("Usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setText("Repetir Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtnick.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        txtpassword1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));

        txtpassword2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setText("Cedula:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtnombre.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, -1));

        txtapellido.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 140, -1));

        txtcedula.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 140, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setText("Pregunta N°1:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, -1));

        cmbpregunta1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbpregunta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        cmbpregunta1.setBorder(null);
        getContentPane().add(cmbpregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 213, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("Pregunta N°2:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setText("Pregunta N°3:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 100, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setText("Pregunta N°4:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 100, -1));

        cmbpregunta2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbpregunta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cmbpregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 213, -1));

        cmbpregunta3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbpregunta3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cmbpregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 210, -1));

        cmbpregunta4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbpregunta4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cmbpregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 210, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Tipo de Usuario:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 130, 20));

        cmbusuario.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.." }));
        cmbusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        getContentPane().add(cmbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 150, 30));

        txtrespuesta4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtrespuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 210, -1));

        txtrespuesta3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtrespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespuesta3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtrespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 210, -1));

        txtrespuesta2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtrespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 210, -1));

        txtrespuesta1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(txtrespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 213, -1));

        btnregistrar.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 110, 30));

        btnsalir.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 80, 30));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("Cod:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102), new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)), "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, 160));

        txtcod.setEditable(false);
        txtcod.setBackground(new java.awt.Color(204, 51, 255));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 20, -1));

        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102), new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 180));

        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 204), new java.awt.Color(102, 0, 102), new java.awt.Color(153, 0, 204), new java.awt.Color(102, 0, 102)), "Preguntas de Seguridad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 350, 350));

        jLabel16.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 255));
        jLabel16.setText("REGISTRO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/helado1.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 670, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespuesta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespuesta3ActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
String nick,pass,pass1,nomb,ape,ced,resp1,resp2,resp3,resp4;

      nick= txtnick.getText();
      pass=txtpassword1.getText().toString();
      pass1=txtpassword2.getText().toString();
      ced= txtcedula.getText();
      nomb=txtnombre.getText();
      ape=txtapellido.getText();
      resp1=txtrespuesta1.getText();
      resp2=txtrespuesta2.getText();
      resp3=txtrespuesta3.getText();
      resp4=txtrespuesta4.getText();
      
      
      if( txtnick.getText().equals("") || cmbusuario.getSelectedItem().equals("") || txtpassword1.toString().equals("")
              || txtpassword2.toString().equals("")){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe llenar todo los campos\n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        txtnick.requestFocus();
      }

        else {
        
       
        String sSQL,sSQL1,sSQL2,sSQL3,sSQL4,sSQL5;
      
      
              if(pass.equals(pass1)){
       numeros();          
      sSQL=(" INSERT INTO tb_user VALUES('"+txtcod.getText()+"','"+nick+"','"+pass+"','"+cmbusuario.getSelectedIndex()+"')");
      
      sSQL1=("INSERT INTO tb_usuarior VALUES ('"+0+"','"+nomb+"','"+ape+"','"+ced+"','"+txtcod.getText()+"')");
      
     sSQL2=("INSERT INTO tb_respuestas VALUES ('"+0+"','"+resp1+"','"+cmbpregunta1.getSelectedIndex()+"','"+txtcod.getText()+"')");
     sSQL3=("INSERT INTO tb_respuestas VALUES ('"+0+"','"+resp2+"','"+cmbpregunta2.getSelectedIndex()+"','"+txtcod.getText()+"')");
     sSQL4=("INSERT INTO tb_respuestas VALUES ('"+0+"','"+resp3+"','"+cmbpregunta3.getSelectedIndex()+"','"+txtcod.getText()+"')");
     sSQL5=("INSERT INTO tb_respuestas VALUES ('"+0+"','"+resp4+"','"+cmbpregunta4.getSelectedIndex()+"','"+txtcod.getText()+"')");
      
      try{
     Statement st = cn.createStatement();
        st.executeUpdate(sSQL);       
        st.executeUpdate(sSQL1);
        st.executeUpdate(sSQL2);
        st.executeUpdate(sSQL3);
        st.executeUpdate(sSQL4);
        st.executeUpdate(sSQL5);

javax.swing.JOptionPane.showMessageDialog(this,
                "Registro exitoso\n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
      
      }  catch (SQLException ex) {
                java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
              }  
              else{
              javax.swing.JOptionPane.showMessageDialog(this,
                "Contraseña no coincide\n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
             }
              }  
           limpiar();
           
        }

        /**
        * @param args the command line arguments
        */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new RegistrarUsuario().setVisible(true);
                }
            });        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        new inicio().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
char c=evt.getKeyChar();
if (c<'0' || c>'9' )
        evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
char c=evt.getKeyChar();
if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' '))
        evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
char c=evt.getKeyChar();
if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' '))
        evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyTyped

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbpregunta1;
    private javax.swing.JComboBox<String> cmbpregunta2;
    private javax.swing.JComboBox<String> cmbpregunta3;
    private javax.swing.JComboBox<String> cmbpregunta4;
    private javax.swing.JComboBox<String> cmbusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnick;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword1;
    private javax.swing.JPasswordField txtpassword2;
    private javax.swing.JTextField txtrespuesta1;
    private javax.swing.JTextField txtrespuesta2;
    private javax.swing.JTextField txtrespuesta3;
    private javax.swing.JTextField txtrespuesta4;
    // End of variables declaration//GEN-END:variables

    private PreparedStatement setString(int i, String cod) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private PreparedStatement setInt(int i, Object selectedItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
